on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Lint
      run: |
        pip3 install flake8
        flake8
    - name: Test
      run: |
        python3 -munittest
