on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - uses: actions/setup-python@v1
      with:
        python-version: 3.6
    - name: Lint
      run: |
        pip install flake8
        flake8
    - name: Test
      run: |
        python3 -munittest
